### ISSUE TITLE
Testes não terminam (loop?)

### ISSUE THREAD

**Issue by kyriosdata** [caiobas/cs-2019-01#17]
Na linha de comandos

```bash
mvn test -Djava.version=10
```

não retorna. Observe que estou usando versão 10. Você usa algo específico da 12?

**Comment by caiobas** [comment]
Havia um erro professor. Estão rodando perfeitamente agora. Pelo menos aqui.

**Comment by kyriosdata** [comment]
Olá Caio,

guarde este "pelo menos aqui", pelo menos por enquanto, pois temos que
remover esta possibilidade, vermos como, por exemplo, por meio de
integração contínua.

Fábio
