### ISSUE TITLE
Remova arquivo checkstyle.xml do diretório resources

### ISSUE THREAD

**Issue by kyriosdata** [caiobas/cs-2019-01#24]
Arquivo de configuração do checkstyle deve estar em outro local (veja orientação por meio do SIGAA, enviada a todos os estudantes).

**Comment by caiobas** [comment]
Depois que alterei para o modo que o senhor pediu o comando do checkstyle e do pmd não funcionam mais. Segue erro:

checkstyle -> 
 An error has occurred in Checkstyle report generation.: Failed during checkstyle configuration: cannot initialize module TreeWalker - Property 'ignoredAnnotations' in module DesignForExtension does not exist, please check the documentation

pmd -> 
Execution default-cli of goal org.apache.maven.plugins:maven-pmd-plugin:3.11.0:pmd failed: Unable to find referenced rule UseUnderscoresInNumericLiterals; perhaps the rule name is mispelled?

**Comment by kyriosdata** [comment]
Acredito que os plugins nao estao configurados conforme o projeto exemplo.
Veja se estao, de fato, iguais.

Em ter, 28 de mai de 2019 02:18, caiobas <notifications@github.com>
escreveu:
