### ISSUE TITLE
Observe e "replique"

### ISSUE THREAD

**Issue by kyriosdata** [caiobas/cs-2019-01#27]
Você escreveu 

```java
final int limiteMaximo = 9999;
if (numero < 0 || numero > limiteMaximo) {
	throw new IllegalArgumentException(
		"Numero fora da exigencia:" + numero
		+ " Esperado numero entre 0 e 9999.");
}
final int auxiliar = 100;
final int primDez = numero / auxiliar;
final int segDez = numero % auxiliar;
final int resultado = (int) Math.pow(primDez + segDez, 2);

return resultado == numero;
```

MAS PODERIA SER MAIS LEGÍVEL ASSIM? 

```java
if (foraDaFaixa(numero)) {
	throw new IllegalArgumentException(
		"Numero fora da exigencia:" + numero
		+ " Esperado numero entre 0 e 9999.");
}

final int primeiraDez = numero / 100;
final int segundaDez = numero % 100;
final int quadrado = (primeiraDez + segundaDez) * (primeiraDez + segundaDez);

return quadrado == numero;
```

**Comment by kyriosdata** [comment]
Também acredito que é possível melhor os nomes primeiraDez e segundaDez, por exemplo. Pois se tratam dos dois primeiros dígitos e os dois dígitos segintes, os menos significativos. Algo como "maisSignificativos" e "menosSignitifcativos". Apenas um pensamento registrado.

**Comment by caiobas** [comment]
Acredito que dessa maneira não ficaria muito legal, pois existem várias algoritmos que podem utilizar dessa função "foraDaFaixa", portanto precisaria criar caso especifico desta função para suprir cada algoritmo.

> Você escreveu
> 
> ```java
> final int limiteMaximo = 9999;
> if (numero < 0 || numero > limiteMaximo) {
> 	throw new IllegalArgumentException(
> 		"Numero fora da exigencia:" + numero
> 		+ " Esperado numero entre 0 e 9999.");
> }
> final int auxiliar = 100;
> final int primDez = numero / auxiliar;
> final int segDez = numero % auxiliar;
> final int resultado = (int) Math.pow(primDez + segDez, 2);
> 
> return resultado == numero;
> ```
> 
> MAS PODERIA SER MAIS LEGÍVEL ASSIM?
> 
> ```java
> if (foraDaFaixa(numero)) {
> 	throw new IllegalArgumentException(
> 		"Numero fora da exigencia:" + numero
> 		+ " Esperado numero entre 0 e 9999.");
> }
> 
> final int primeiraDez = numero / 100;
> final int segundaDez = numero % 100;
> final int quadrado = (primeiraDez + segundaDez) * (primeiraDez + segundaDez);
> 
> return quadrado == numero;
> ```

**Comment by caiobas** [comment]
Sobre os nomes destas variáveis, eles se dão pelo fato de serem respectivamente a primeira e segunda dezena do número a ser analisado:
1345 -> 
Primeira dezena: 13
Segunda dezena: 45

Portanto não há definição de qual seria mais significativo ou menos significativo neste contexto. 


> Também acredito que é possível melhor os nomes primeiraDez e segundaDez, por exemplo. Pois se tratam dos dois primeiros dígitos e os dois dígitos segintes, os menos significativos. Algo como "maisSignificativos" e "menosSignitifcativos". Apenas um pensamento registrado.

**Comment by kyriosdata** [comment]
Nao estamos economizanso metodos em detrimento da legibilidade, certo?

Se houver possibilidade de reutilizacao, entao seria ainda melhor.

Ou seja, precisamos de outro argumento para evitar essa forma, ou nao?

Em ter, 28 de mai de 2019 02:40, caiobas <notifications@github.com>
escreveu:
